import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Container, Grid, Link, List, ListItem, Paper, Typography } from '@mui/material'
//interestSectionBG
import interestSectionBG from '../../assets/home/interestSectionBG.png'
import section1Img from '../../assets/home/career-screen.png'
import section2Img from '../../assets/home/pathways.png'
import section3Img from '../../assets/home/course-screen.png'
import section4Img from '../../assets/home/college-screen.png'
import section5Img from '../../assets/home/inertia-screen.png'
import section6Img from '../../assets/home/test-screen.png'
import ButtonComponent from '@/libs/material-ui/components/button'

const inter = Inter({ subsets: ['latin'] })

export default function TermsOfServicesComponent() {
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid  style={{backgroundColor:'#f3f7fe'}} container spacing={2}  padding={10}>
            <Grid item md={12}>
                <h1 style={{textAlign:'center'}}>Terms of Services</h1>
                </Grid></Grid>
     
        <div
     
      >
         <Container maxWidth="lg">
      <Grid container spacing={2}  paddingTop={10}>
            <Grid item md={12}>
              <h3 style={{color:'#112152',textAlign:'left'}}>1.Disclaimer</h3>
              
              <List sx={{ listStyleType: 'disc', pl: 4 }} style={{fontSize:16}}>
              
              <ListItem sx={{ display: 'list-item' }} style={{fontSize:16}}>
              We use our reasonable endeavors to ensure the accuracy of the information provided on the brainwonders.in service
            </ListItem>
            <ListItem sx={{ display: 'list-item' }} style={{fontSize:16}}>
            We do not warrant or guarantee the accuracy, reliability or legality of any of the information contained in the brainwonders.in. </ListItem>
            <ListItem sx={{ display: 'list-item' }} style={{fontSize:16}}>
            We make no warranty that the contents of this site are free from infection by viruses or anything else which has contaminating or destructive properties. </ListItem>
            <ListItem sx={{ display: 'list-item' }} style={{fontSize:16}}>
            We reserve the right, at its discretion, from time to time to make changes to the information provided on the brainwonders.in service, or to alter the nature of the brainwonders.in service. </ListItem>
           
            </List>
            <h3 style={{color:'#112152',textAlign:'left'}}>2.Intellectual Property</h3>
              
              <List sx={{ listStyleType: 'disc', pl: 4 }} style={{fontSize:16}}>
              
              <ListItem sx={{ display: 'list-item' }} style={{fontSize:16}}>
              The data and information contained on the brainwonders.in service, the software used to operate it and the trade marks, logos and other intellectual property used in connection with it are the property of brainwonders.in. No license of any such intellectual property rights is granted to you as a result of your use of the brainwonders.in service. All the information on the website brainwonders.in like careers data, colleges data, assessment tests, assessment reports etc are proprietary of brainwonders.in (Brainwonders) and hence any infringement of copyright would be liable for civil action.</ListItem>
            </List>
            </Grid>
            </Grid>
            </Container>

      </div>
    </>
  )
}
