import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Grid } from '@mui/material'
//interestSectionBG
import interestSectionBG from '../../assets/home/interestSectionBG.png'




const inter = Inter({ subsets: ['latin'] })

export default function HomeComponent() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div style={{background:"#013388",width:'100%',color:"white",height:500}}>
     <Grid container spacing={2}>
  <Grid item xs={7}>
<Image src={interestSectionBG} width={820} height={450} alt={"home background"}/>
  </Grid>
  <Grid item xs={5}>
  
  </Grid>

</Grid>

     </div>
    
    </>
  )
}
