import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
// import styles from '@/styles/Home.Header.css'
import DrawerAppBar from '@/libs/material-ui/components/header'
import ButtonComponent from '@/libs/material-ui/components/button'
import HomeComponent from './home'
import TermsOfServicesComponent from './terms-of-services'
import PrivacyPolicyComponent from './private-policy'




export default function Home() {
  return (
    <>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DrawerAppBar/>
     <HomeComponent/>
    </>
  )
}
