import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Container, Grid, Link, List, ListItem, Paper, Typography } from '@mui/material'
//interestSectionBG
import interestSectionBG from '../../assets/home/interestSectionBG.png'
import section1Img from '../../assets/home/career-screen.png'
import section2Img from '../../assets/home/pathways.png'
import section3Img from '../../assets/home/course-screen.png'
import section4Img from '../../assets/home/college-screen.png'
import section5Img from '../../assets/home/inertia-screen.png'
import section6Img from '../../assets/home/test-screen.png'
import ButtonComponent from '@/libs/material-ui/components/button'

const inter = Inter({ subsets: ['latin'] })

export default function PrivacyPolicyComponent() {
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid  style={{backgroundColor:'#f3f7fe'}} container spacing={2}  padding={10}>
            <Grid item md={12}>
                <h1 style={{textAlign:'center',color:'#112152'}}>Privacy Policy</h1>
                </Grid></Grid>
     
        <div
     
      >
         <Container maxWidth="lg">
      <Grid container spacing={2}  paddingTop={3}>
            <Grid item md={12}>
            <List>
                <ListItem>
                   <p>
          (a) This Privacy Policy (“Policy”) outlines Thecareerhub’s (“Thecareerhub”, “we”, or “us”) practice in relation to the storage, use, processing, and disclosure of personal data that you have chosen to share with us when you access our website brainwonders.in, or personal data that we may have access to in relation to your use of Platform and access to our range of financial products and services (collectively, “Services”).
          </p> 
                </ListItem>
                <ListItem>
                    <p>
          (b) At Thecareerhub, we are committed to protecting your personal data and respecting your privacy. Please read the following terms of the Policy carefully to understand our practices regarding your personal data and how we will treat it. This policy sets out the basis on which any personal data we collect from you or about you, or that you provide to us, will be processed by us.
          </p>
                </ListItem>
                <ListItem>
                <p>
          (c) Capitalised words in the Policy shall have the same meaning ascribed to them in the Terms of Service (“Terms”), available at [link] Please read this Policy in consonance with the Terms
          </p>
                </ListItem>
                <ListItem>
                <p>
          (d) By using the Platform, you consent to the collection, storage, use, and disclosure of your personal data, in accordance with, and are agreeing to be bound by this Policy. We will not collect any information from you, except where it is knowingly and explicitly provided by you.
          </p>
                </ListItem>
                <ListItem>
                <p>
          (e) This Policy together with any terms of the arrangement we have with you applies to your use of the Services.
          </p>
                </ListItem>
              

                </List> 
          
          
       
          
         
          
          <h3 style={{color:'#112152',textAlign:'left'}}>The data we collect about you</h3>
          <List>
          <ListItem>
             <p>
          (a) Personal data, or personal information, means any information about an individual from which that person can be identified. It does not include data where the identity has been removed – for example, anonymous data.
          </p>        
        </ListItem>
        <ListItem>
              <p>
          (b) We may collect, use, store and transfer different kinds of personal data about you to provide you with or in connection with the Services, that you may choose to provide to us. Such personal data includes:
          </p>     
        
        </ListItem>
            <ListItem style={{paddingLeft:45}}>
            (i) Data pertaining to your identity and related data, such as your first and last name, username or similar identifiers, gender, title, passwords, purchases or orders of or through our Services, feedback, survey responses, etc.;
            </ListItem>
            <ListItem style={{paddingLeft:45}}>
            (ii) Contact data, including email addresses, phone numbers, delivery addresses, business addresses, social media information, etc.;
            </ListItem>
            <ListItem style={{paddingLeft:45}}>
            (iii) Transaction data, including details about payments to and from you and details of the services you have purchased;
            </ListItem>
            <ListItem style={{paddingLeft:45}}>
            (iv) Financial data, including the details of the financial products you have availed via the Platform, bank account information, payment methods, and card details
            </ListItem> 
          </List>
          <List sx={{ listStyleType: 'disc', pl: 4 }}>
              
                <ListItem sx={{ display: 'list-item' }}>
                SMS – SMSs containing financial transaction data;
            </ListItem>
            <ListItem sx={{ display: 'list-item' }}>
            Location – location data recorded on your device;
            </ListItem>
            <ListItem sx={{ display: 'list-item' }}>
            Device Information – including hardware model, operating system and version, IMEI and serial numbers; user profile information, IP addresses, browser types and versions, time zone settings, Wi-Fi and mobile networks;
            </ListItem>
            <ListItem sx={{ display: 'list-item' }}>
            What are the advantages of the Brainwonders Online Aptitude Test?
            </ListItem>
            <ListItem sx={{ display: 'list-item' }}>
            How accurate is the dermatoglyphics multiple intelligences test?
            </ListItem>
           
            </List>
         <List>
         <ListItem style={{paddingLeft:45}}>
         (vi) Usage data, including information about how you use our Services; and
         </ListItem>
         <ListItem style={{paddingLeft:45}}>
         (vii) Marketing and communications data, including your preferences in receiving marketing from us and our third parties and your communication preferences.
         </ListItem>
         </List>
         <h3 style={{color:'#112152',textAlign:'left'}}>Grievance Officer</h3>
<p>
You may contact us at <b>support@thecareerhub.com</b> with any enquiry relating to this Policy or an enquiry relating to your personal information (including reviewing or updating). You can also do so by writing to our Grievance Officer, established in accordance with the Information Technology Act, 2000 and rules made thereunder, at the address provided below
</p>
<p>Name : Manish Naidu</p>
<p>Address : A 101, Suchita Enclave, Jai Maharashtra Nagar, Off Chandavarkar Road, Borivali West, Mumbai, Maharashtra (400092)</p>
            </Grid>
            </Grid>
            </Container>

      </div>
    </>
  )
}
